import 'package:flutter/foundation.dart';

class AppLocalizations {
  static final Map<String, String> languages = {
    'en': 'English',
    'hi': 'हिन्दी (Hindi)',
    'bn': 'বাংলা (Bengali)',
    'te': 'తెలుగు (Telugu)',
    'ta': 'தமிழ் (Tamil)',
    'mr': 'मराठी (Marathi)',
    'gu': 'ગુજરાતી (Gujarati)',
    'kn': 'ಕನ್ನಡ (Kannada)',
    'ml': 'മലയാളം (Malayalam)',
    'pa': 'ਪੰਜਾਬੀ (Punjabi)',
    'or': 'ଓଡ଼ିଆ (Odia)',
    'as': 'অসমীয়া (Assamese)',
    'ur': 'اردو (Urdu)',
    'sa': 'संस्कृतम् (Sanskrit)',
    'ne': 'नेपाली (Nepali)',
    'sd': 'सिन्धी (Sindhi)',
    'ks': 'कश्मीरी (Kashmiri)',
    'kok': 'कोंकणी (Konkani)',
    'doi': 'डोगरी (Dogri)',
    'mni': 'মণিপুরী (Manipuri)',
    'brx': 'बड़ो (Bodo)',
    'mai': 'मैथिली (Maithili)',
    'sat': 'संथाली (Santali)',
  };

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Mandi Predictor',
      'dashboard': 'Dashboard',
      'farmer_advisor': 'Farmer Advisor',
      'weather': 'Today\'s Weather',
      'trends': 'My Crop Trends (Next 7 Days)',
      'govt_rate': 'Official government rate not yet updated for today.',
      'loading': 'Loading...',
      'retry': 'Retry',
      'get_forecast': 'Get 7-Day Price Forecast',
      'calculate_profit': 'Calculate Best Profit',
      'select_state': 'Select State',
      'select_mandi': 'Select Mandi',
      'select_commodity': 'Select Commodity',
      'quantity': 'Quantity',
      'storage_days': 'Max Storage Days',
      'storage_cost': 'Storage Cost/Day (₹)',
      'transport_cost': 'Transport Cost/Km (₹)',
      'distance': 'Distance to Mandi (Km)',
      'results': 'Results',
      'price_trend': 'Price Trend',
      'rec_action': 'RECOMMENDED ACTION',
      'net_profit': 'Net Profit',
      'details': 'Details',
      'unit_q': 'Quintal',
      'unit_kg': 'Kg',
      'change_ling': 'Change Language',
      'farmer_role': 'Farmer',
      'profile': 'My Profile',
      'field_assistant': 'Field Assistant',
      'logout': 'Logout',
      'today_label': "Today's Rate: ",
      'farmer_profile_opt': 'Farmer Profile Optimization',
      'enter_details': 'Enter details to calculate profit',
      'quantity_q': 'Quantity (Quintals)',
      'max_storage': 'Max Storage (Days)',
      'smart_advisory': 'Smart Advisory',
      'ask_assistant': 'Ask Assistant',
      'col_date': 'Date',
      'col_price': 'Price',
      'col_trend': 'Trend',
      'not_updated': 'Official government rate not yet updated for today.',
      'est': '(Est)',
      'no_alerts': 'No high-confidence alerts today.',
    },
    // Hindi
    'hi': {
      'app_title': 'मंडी पूर्वानुकूलक',
      'dashboard': 'डैशबोर्ड',
      'farmer_advisor': 'किसान सलाहकार',
      'weather': 'आज का मौसम',
      'trends': 'मेरी फसल रुझान (अगले 7 दिन)',
      'govt_rate': 'आज के लिए आधिकारिक सरकारी दर अभी तक अपडेट नहीं की गई है।',
      'loading': 'लोड हो रहा है...',
      'retry': 'पुनः प्रयास करें',
      'get_forecast': '7-दिवसीय मूल्य पूर्वानुमान प्राप्त करें',
      'calculate_profit': 'सर्वोत्तम लाभ की गणना करें',
      'select_state': 'राज्य चुनें',
      'select_mandi': 'मंडी चुनें',
      'select_commodity': 'फसल चुनें',
      'quantity': 'मात्रा',
      'storage_days': 'अधिकतम भंडारण दिन',
      'storage_cost': 'भंडारण लागत/दिन (₹)',
      'transport_cost': 'परिवहन लागत/किमी (₹)',
      'distance': 'मंडी की दूरी (किमी)',
      'results': 'परिणाम',
      'price_trend': 'मूल्य रुझान',
      'rec_action': 'अनुशंसित कर्य',
      'net_profit': 'शुद्ध लाभ',
      'details': 'विवरण',
      'unit_q': 'क्विंटल',
      'unit_kg': 'किग्रा',
      'change_ling': 'भाषा बदलें',
      'farmer_role': 'किसान',
      'profile': 'प्रोफ़ाइल',
      'field_assistant': 'खेत सहायक',
      'logout': 'लॉग आउट',
      'today_label': "आज का भाव: ",
      'farmer_profile_opt': 'लाभ अनुकूलन (Profit Opt)',
      'enter_details': 'लाभ गणना के लिए विवरण दर्ज करें',
      'quantity_q': 'मात्रा (क्विंटल)',
      'max_storage': 'अधिकतम भंडारण (दिन)',
      'smart_advisory': 'स्मार्ट सलाह',
      'ask_assistant': 'सहायक से पूछें',
      'col_date': 'दिनांक',
      'col_price': 'भाव',
      'col_trend': 'रुझान',
      'not_updated': 'आज के लिए आधिकारिक सरकारी दर अभी अपडेट नहीं हुई है।',
      'est': '(अनुमानित)',
      'no_alerts': 'आज कोई महत्वपूर्ण चेतावनी नहीं है।',
    },
    // Telugu
    'te': {
      'app_title': 'మండి ప్రిడిక్టర్',
      'dashboard': 'డాష్‌బోర్డ్',
      'farmer_advisor': 'రైతు సలహాదారు',
      'weather': 'నేటి వాతావరణం',
      'trends': 'నా పంట పోకడలు (వచ్చే 7 రోజులు)',
      'govt_rate': 'నేటి ప్రభుత్వ రేటు ఇంకా నవీకరించబడలేదు.',
      'loading': 'లోడ్ అవుతోంది...',
      'retry': 'మళ్లీ ప్రయత్నించండి',
      'get_forecast': '7 రోజుల ధర అంచనాను పొందండి',
      'calculate_profit': 'ఉత్తమ లాభాన్ని లెక్కించండి',
      'select_state': 'రాష్ట్రాన్ని ఎంచుకోండి',
      'select_mandi': 'మండి ఎంచుకోండి',
      'select_commodity': 'పంటను ఎంచుకోండి',
      'quantity': 'పరిమాణం',
      'storage_days': 'గరిష్ట నిల్వ రోజులు',
      'storage_cost': 'నిల్వ ఖర్చు/రోజు (₹)',
      'transport_cost': 'రవాణా ఖర్చు/కిమీ (₹)',
      'distance': 'మండికి దూరం (కిమీ)',
      'results': 'ఫలితాలు',
      'price_trend': 'ధర సరళి',
      'rec_action': 'సిఫార్సు చేసిన చర్య',
      'net_profit': 'నికర లాభం',
      'details': 'వివరాలు',
      'unit_q': 'క్వింటాల్',
      'unit_kg': 'కిలో',
      'change_ling': 'భాషను మార్చండి',
      'farmer_role': 'రైతు',
      'profile': 'ప్రొఫైల్',
      'field_assistant': 'క్షేత్ర సహాయకుడు',
      'logout': 'లాగ్ అవుట్',
      'today_label': "నేటి ధర: ",
      'farmer_profile_opt': 'రైతు ప్రొఫైల్ ఆప్టిమైజేషన్',
      'enter_details': 'లాభాన్ని లెక్కించడానికి వివరాలను నమోదు చేయండి',
      'quantity_q': 'పరిమాణం (క్వింటాల్స్)',
      'max_storage': 'గరిష్ట నిల్వ (రోజులు)',
      'smart_advisory': 'స్మార్ట్ సలహా',
      'ask_assistant': 'అసిస్టెంట్‌ని అడగండి',
      'col_date': 'తేదీ',
      'col_price': 'ధర',
      'col_trend': 'సరళి',
      'not_updated': 'ఈ రోజు అధికారిక ప్రభుత్వ రేటు ఇంకా నవీకరించబడలేదు.',
      'est': '(అంచనా)',
      'no_alerts': 'ఈ రోజు ఆందోళన కలిగించే హెచ్చరికలు ఏవీ లేవు.',
    },
    // Tamil
    'ta': {
      'dashboard': 'டாஷ்போர்டு',
      'farmer_advisor': 'விவசாய ஆலோசகர்',
      'weather': 'இன்றைய வானிலை',
      'trends': 'பயிர் விலை போக்கு (அடுத்த 7 நாட்கள்)',
      'get_forecast': '7 நாள் விலை முன்னறிவிப்பு',
      'calculate_profit': 'லாபத்தை கணக்கிடு',
      'select_state': 'மாநிலம் தேர்வு',
      'select_mandi': 'சந்தை தேர்வு',
      'select_commodity': 'பயிர் தேர்வு',
      'unit_q': 'குவிண்டால்',
      'unit_kg': 'கிலோ',
      'change_ling': 'மொழியை மாற்றவும்',
      'farmer_profile_opt': 'விவசாயி சுயவிவரம்',
      'enter_details': 'விவரங்களை உள்ளிடவும்',
      'quantity_q': 'அளவு (குவிண்டால்)',
      'max_storage': 'அதிகபட்ச சேமிப்பு (நாட்கள்)',
      'smart_advisory': 'ஸ்மார்ட் ஆலோசனை',
      'ask_assistant': 'உதவியாளரிடம் கேளுங்கள்',
      'col_date': 'தேதி',
      'col_price': 'விலை',
      'col_trend': 'போக்கு',
      'not_updated': 'அரசு விலை இன்னும் புதுப்பிக்கப்படவில்லை.',
      'est': '(மதிப்பீடு)',
      'no_alerts': 'எச்சரிக்கைகள் இல்லை.',
    },
    // Marathi
    'mr': {
      'dashboard': 'डॅशबोर्ड',
      'farmer_advisor': 'शेतकरी सल्लागार',
      'weather': 'आजचे हवामान',
      'trends': 'पिकांचे कल (पुढील 7 दिवस)',
      'get_forecast': '7-दिवसीय किंमत अंदाज मिळवा',
      'calculate_profit': 'नफा मोजा',
      'select_state': 'राज्य निवडा',
      'select_mandi': 'मंडी निवडा',
      'select_commodity': 'पीक निवडा',
      'unit_q': 'क्विंटल',
      'unit_kg': 'किग्रॅ',
      'change_ling': 'भाषा बदला',
      'farmer_profile_opt': 'शेतकरी प्रोफाइल',
      'enter_details': 'तपशील प्रविष्ट करा',
      'quantity_q': 'प्रमाण (क्विंटल)',
      'max_storage': 'जास्तीत जास्त साठवण (दिवस)',
      'smart_advisory': 'स्मार्ट सल्ला',
      'ask_assistant': 'सहायकाला विचारा',
      'col_date': 'तारीख',
      'col_price': 'भाव',
      'col_trend': 'कल',
      'not_updated': 'शासकीय दर अद्याप अपडेट केलेले नाहीत.',
      'est': '(अंदाज)',
      'no_alerts': 'कोणतीही चेतावणी नाही.',
    },
    // Kannada
    'kn': {
      'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'farmer_advisor': 'ರೈತ ಸಲಹೆಗಾರ',
      'weather': 'ಇಂದಿನ ಹವಾಮಾನ',
      'trends': 'ಬೆಳೆ ಬೆಲೆ ಇಳಿಕೆ/ಏರಿಕೆ (ಮುಂದಿನ 7 ದಿನಗಳು)',
      'get_forecast': '7 ದಿನದ ಬೆಲೆ ಮುನ್ಸೂಚನೆ',
      'unit_q': 'ಕ್ವಿಂಟಾಲ್',
      'unit_kg': 'ಕೆಜಿ',
      'change_ling': 'ಭಾಷೆ ಬದಲಿಸಿ',
      'farmer_profile_opt': 'ರೈತ ಪ್ರೊಫೈಲ್',
      'enter_details': 'ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ',
      'quantity_q': 'ಪ್ರಮಾಣ (ಕ್ವಿಂಟಾಲ್)',
      'max_storage': 'ಗರಿಷ್ಠ ಸಂಗ್ರಹಣೆ (ದಿನಗಳು)',
      'smart_advisory': 'ಸ್ಮಾರ್ಟ್ ಸಲಹೆ',
      'ask_assistant': 'ಸಹಾಯಕನನ್ನು ಕೇಳಿ',
      'col_date': 'ದಿನಾಂಕ',
      'col_price': 'ಬೆಲೆ',
      'col_trend': 'ಪ್ರವೃತ್ತಿ',
      'not_updated': 'ಸರ್ಕಾರಿ ದರ ಇನ್ನೂ ನವೀಕರಿಸಲಾಗಿಲ್ಲ.',
      'est': '(ಅಂದಾಜು)',
      'no_alerts': 'ಯಾವುದೇ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ.',
    },
    // Bengali
    'bn': {
      'dashboard': 'ড্যাশবোর্ড',
      'farmer_advisor': 'কৃষক পরামর্শদাতা',
      'weather': 'আজকের আবহাওয়া',
      'trends': 'ফসলের প্রবণতা (আগামী 7 দিন)',
      'get_forecast': '7 দিনের দামের পূর্বাভাস পান',
      'unit_q': 'কুইন্টাল',
      'unit_kg': 'কেজি',
      'change_ling': 'ভাষা পরিবর্তন করুন',
      'farmer_profile_opt': 'কৃষক প্রোফাইল',
      'enter_details': 'বিবরণ লিখুন',
      'quantity_q': 'পরিমাণ (কুইন্টাল)',
      'max_storage': 'সর্বোচ্চ স্টোরেজ (দিন)',
      'smart_advisory': 'স্মার্ট পরামর্শ',
      'ask_assistant': 'সহকারীকে জিজ্ঞাসা করুন',
      'col_date': 'তারিখ',
      'col_price': 'দাম',
      'col_trend': 'প্রবণতা',
      'not_updated': 'সরকারি রেট এখনও আপডেট হয়নি।',
      'est': '(আনুমানিক)',
      'no_alerts': 'কোন সতর্কতা নেই।',
    },
    // Gujarati
    'gu': {
      'dashboard': 'ડેશબોર્ડ',
      'farmer_advisor': 'ખેડૂત સલાહકાર',
      'weather': 'આજનું હવામાન',
      'trends': 'પાક પ્રવાહો (આગામી 7 દિવસ)',
      'get_forecast': '7 દિવસની કિંમતની આગાહી',
      'unit_q': 'ક્વિન્ટલ',
      'unit_kg': 'કિલો',
      'change_ling': 'ભાષા બદલો',
      'farmer_profile_opt': 'ખેડૂત પ્રોફાઇલ',
      'enter_details': 'વિગતો દાખલ કરો',
      'quantity_q': 'જથ્થો (ક્વિન્ટલ)',
      'max_storage': 'મહત્તમ સંગ્રહ (દિવસો)',
      'smart_advisory': 'સ્માર્ટ સલાહ',
      'ask_assistant': 'મદદનીશને પૂછો',
      'col_date': 'તારીખ',
      'col_price': 'ભાવ',
      'col_trend': 'વલણ',
      'not_updated': 'સરકારી દર હજુ અપડેટ થયા નથી.',
      'est': '(અંદાજિત)',
      'no_alerts': 'કોઈ ચેતવણી નથી.',
    },
    // Punjabi
    'pa': {
      'dashboard': 'ਡੈਸ਼ਬੋਰਡ',
      'farmer_advisor': 'ਕਿਸਾਨ ਸਲਾਹਕਾਰ',
      'weather': 'ਅੱਜ ਦਾ ਮੌਸਮ',
      'trends': 'ਫਸਲ ਦੇ ਰੁਝਾਨ (ਅਗਲੇ 7 ਦਿਨ)',
      'unit_q': 'ਕਵਿੰਟਲ',
      'unit_kg': 'ਕਿਲੋ',
      'change_ling': 'ਭਾਸ਼ਾ ਬਦਲੋ',
      'farmer_profile_opt': 'ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ',
      'enter_details': 'ਵੇਰਵੇ ਭਰੋ',
      'quantity_q': 'ਮਾਤਰਾ (ਕਵਿੰਟਲ)',
      'max_storage': 'ਵੱਧ ਤੋਂ ਵੱਧ ਸਟੋਰੇਜ (ਦਿਨ)',
      'smart_advisory': 'ਸਮਾਰਟ ਸਲਾਹ',
      'ask_assistant': 'ਸਹਾਇਕ ਨੂੰ ਪੁੱਛੋ',
      'col_date': 'ਮਿਤੀ',
      'col_price': 'ਕੀਮਤ',
      'col_trend': 'ਰੁਝਾਨ',
      'not_updated': 'ਸਰਕਾਰੀ ਰੇਟ ਅਜੇ ਅਪਡੇਟ ਨਹੀਂ ਹੋਇਆ।',
      'est': '(ਅਨੁਮਾਨਿਤ)',
      'no_alerts': 'ਕੋਈ ਚੇਤਾਵਨੀ ਨਹੀਂ।',
    },
    // Malayalam
    'ml': {
      'dashboard': 'ഡാഷ്ബോർഡ്',
      'farmer_advisor': 'കർഷക ഉപദേശകൻ',
      'weather': 'ഇന്നത്തെ കാലാവസ്ഥ',
      'unit_q': 'ക്വിന്റൽ',
      'unit_kg': 'കിലോ',
      'change_ling': 'ഭാഷ മാറ്റുക',
      'farmer_profile_opt': 'കർഷക പ്രൊഫൈൽ',
      'enter_details': 'വിശദാംശങ്ങൾ നൽകുക',
      'quantity_q': 'അളവ് (ക്വിന്റൽ)',
      'max_storage': 'പരമാവധി സംഭരണം (ദിവസങ്ങൾ)',
      'smart_advisory': 'സ്മാർട്ട് ഉപദേശം',
      'ask_assistant': 'സഹായിയോട് ചോദിക്കുക',
      'col_date': 'തീയതി',
      'col_price': 'വില',
      'col_trend': 'ട്രെൻഡ്',
      'not_updated': 'സർക്കാർ നിരക്ക് ഇതുവരെ അപ്‌ഡേറ്റ് ചെയ്തിട്ടില്ല.',
      'est': '(ഏകദേശം)',
      'no_alerts': 'മുന്നറിയിപ്പുകളൊന്നുമില്ല.',
    },
  };

  static String get(String code, String key) {
    if (_localizedValues.containsKey(code) &&
        _localizedValues[code]!.containsKey(key)) {
      return _localizedValues[code]![key]!;
    }
    // Fallback to English
    return _localizedValues['en']![key] ?? key;
  }
}

// Global Notifier for Locale
final ValueNotifier<String> localeNotifier = ValueNotifier<String>('en');
