class CommodityList {
  static const List<String> all = [
    // FOOD GRAINS
    "Arhar",
    "Arhar Dal Split",
    "Bajra",
    "Barley",
    "Basmati rice",
    "Buck Wheat",
    "Chakhao Or Black Rice",
    "Chana Dal Split",
    "Chana whole",
    "Horse Gram",
    "Jowar",
    "Kabuli Chana Whole",
    "Lobia",
    "Maize",
    "Masoor whole",
    "Moong Dal Split",
    "Moong whole",
    "Moth",
    "Oats Raw",
    "Paddy",
    "Ragi",
    "Rajma",
    "Urad Dal Split", "Urad whole", "Wheat", "White Peas",

    // OILSEEDS
    "Castor seed",
    "Cotton Seed",
    "Kusum seed",
    "Linseed",
    "Mustard seed",
    "Neem Seeds",
    "Nigar Seed",
    "Peanut kernel",
    "Pongam seeds",
    "Rapeseed",
    "Sal Seed",
    "Sesame seed",
    "Soyabean",
    "Sunflower seed",

    // FRUITS
    "Amla",
    "Apple",
    "Apricot",
    "Banana",
    "Ber",
    "Cherry Red / Black",
    "Custard apple",
    "Grapefruit",
    "Grapes",
    "Guava",
    "Jackfruit",
    "Jamun",
    "Kinnow",
    "Lemon",
    "Litchi",
    "Mango",
    "Musk melon",
    "Orange",
    "Papaya",
    "Papaya Raw",
    "Passion Fruit",
    "Peach",
    "Pear",
    "Pineapple",
    "Plum",
    "Pomegranate",
    "Raw Mango",
    "Sapota",
    "Strawberries",
    "Sweet orange",
    "Watermelon",

    // VEGETABLES
    "Cucumber",
    "Curry Leaves",
    "Drumstick",
    "Fenugreek Leaves",
    "Garlic",
    "Gherkin",
    "Jimikand (Suran)",
    "Lobia Pods",
    "Mint Leaves",
    "Mustard leaf",
    "Onion",
    "Aloe Vera",
    "Banana Raw",
    "Beetroot",
    "Bhindi/Okra",
    "Bitter gourd",
    "Bottle gourd",
    "Brinjal",
    "Broccoli/Calabrese",
    "Button Mushroom",
    "Cabbage",
    "Capsicum",
    "Carrots",
    "Cauliflower",
    "Cluster beans",
    "Colocasia vegetable",
    "Coriander leaves",
    "Oyster Mushroom",
    "Pea",
    "Pointed gourd",
    "Potato",
    "Pumpkin",
    "Reddish",
    "Ribbed celery",
    "Ridge Gourd",
    "Safed Petha",
    "Sem",
    "Snake Guard",
    "Spinach",
    "Sponge Gourd",
    "Spring Onion",
    "Sugar Snap Peas",
    "Sweet Corn",
    "Sweet potato",
    "Tapioca",
    "Tinda",
    "Tomato",

    // SPICES
    "Large cardamom",
    "Mace Whole",
    "Poppy Seed",
    "Red chilli",
    "Tejpata",
    "Turmeric",
    "Ajwain",
    "Black Pepper Whole",
    "Cardamoms Whole",
    "Cloves Whole",
    "Coriander whole",
    "Cumin",
    "Dried Raw Mango Slices",
    "Dry Ginger",
    "Fennel seed",
    "Fenugreek seed",
    "Nutmeg Whole",
    "Tamarind", "Saffron",

    // MISCELLANEOUS
    "Anthurium",
    "Arecanut (betel nut)",
    "Bamboo",
    "Betel leaves",
    "Carnation",
    "Chhappan Kaddu",
    "Chironji",
    "Chrysanthemum",
    "Coconut",
    "Coconut with Husk",
    "Cotton",
    "Gerbera",
    "Gladiolus",
    "Groundnut with pods",
    "Guar seed",
    "Hilsa",
    "Isabgol",
    "Jaggery",
    "Jute Seeds",
    "Lily",
    "Mahua flower",
    "Mahua Seed",
    "Marigold",
    "Persimmon",
    "Raisins",
    "Raw Cashew nut",
    "Raw Jute",
    "Rittha",
    "Rose Cut Flower",
    "Safed Musli",
    "Spray Chrysanthemum",
    "Tender coconut",
    "Tuberose", "Tulip", "Walnuts Inshell",
  ];
}
